spring:
  application:
    name: first-come-grant-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
